-- Libris schema
-- Conventions: snake_case, timestamptz, money as integer cents, enums as CHECK-constrained varchar.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ---------- identity ----------

CREATE TABLE users (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username         VARCHAR(32)  NOT NULL UNIQUE,
    password_hash    VARCHAR(72)  NOT NULL,
    display_name     VARCHAR(64)  NOT NULL,
    role             VARCHAR(16)  NOT NULL CHECK (role IN ('ADMIN', 'READER')),
    status           VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'BLOCKED')),
    email            VARCHAR(128),
    phone            VARCHAR(32),
    preferred_locale VARCHAR(8)   NOT NULL DEFAULT 'zh-CN',
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE reader_profiles (
    user_id     BIGINT      PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    reader_type VARCHAR(16) NOT NULL CHECK (reader_type IN ('TEACHER', 'STUDENT')),
    sex         VARCHAR(8),
    birth       DATE,
    address     VARCHAR(128),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE loan_policies (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reader_type         VARCHAR(16) NOT NULL UNIQUE CHECK (reader_type IN ('TEACHER', 'STUDENT')),
    loan_days           INT         NOT NULL CHECK (loan_days > 0),
    max_loans           INT         NOT NULL CHECK (max_loans > 0),
    max_renewals        INT         NOT NULL CHECK (max_renewals >= 0),
    daily_fine_cents    INT         NOT NULL CHECK (daily_fine_cents >= 0),
    block_overdue_count INT         NOT NULL CHECK (block_overdue_count > 0),
    block_fine_cents    INT         NOT NULL CHECK (block_fine_cents > 0),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------- catalogue ----------

CREATE TABLE categories (
    id      INT          PRIMARY KEY,
    code    VARCHAR(4)   NOT NULL UNIQUE,
    name_zh VARCHAR(64)  NOT NULL,
    name_en VARCHAR(128) NOT NULL
);

CREATE TABLE books (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(256) NOT NULL,
    author      VARCHAR(256) NOT NULL,
    publisher   VARCHAR(128) NOT NULL,
    isbn        VARCHAR(20)  NOT NULL,
    intro       TEXT,
    language    VARCHAR(16)  NOT NULL,
    price_cents INT          CHECK (price_cents >= 0),
    pub_date    DATE,
    category_id INT          NOT NULL REFERENCES categories (id),
    cover_url   VARCHAR(512),
    search_vec  tsvector GENERATED ALWAYS AS (
                    to_tsvector('simple',
                        coalesce(title, '') || ' ' || coalesce(author, '') || ' ' || coalesce(publisher, ''))
                ) STORED,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_books_search_vec ON books USING gin (search_vec);
CREATE INDEX idx_books_title_trgm ON books USING gin (title gin_trgm_ops);
CREATE INDEX idx_books_author_trgm ON books USING gin (author gin_trgm_ops);
CREATE INDEX idx_books_category ON books (category_id);
CREATE INDEX idx_books_isbn ON books (isbn);

CREATE TABLE book_copies (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id     BIGINT      NOT NULL REFERENCES books (id) ON DELETE CASCADE,
    barcode     VARCHAR(32) NOT NULL UNIQUE,
    call_number VARCHAR(64) NOT NULL,
    location    VARCHAR(64) NOT NULL,
    status      VARCHAR(16) NOT NULL DEFAULT 'IN_LIBRARY'
                CHECK (status IN ('IN_LIBRARY', 'ON_LOAN', 'ON_HOLD_SHELF', 'LOST')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_copies_book ON book_copies (book_id);

-- ---------- circulation ----------

CREATE TABLE loans (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    copy_id     BIGINT      NOT NULL REFERENCES book_copies (id),
    reader_id   BIGINT      NOT NULL REFERENCES users (id),
    loaned_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    due_at      TIMESTAMPTZ NOT NULL,
    returned_at TIMESTAMPTZ,
    renew_count INT         NOT NULL DEFAULT 0,
    operator_id BIGINT      REFERENCES users (id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- one active loan per physical copy, enforced by the database
CREATE UNIQUE INDEX uq_loans_active_copy ON loans (copy_id) WHERE returned_at IS NULL;
CREATE INDEX idx_loans_reader_active ON loans (reader_id) WHERE returned_at IS NULL;
CREATE INDEX idx_loans_reader ON loans (reader_id);
CREATE INDEX idx_loans_due ON loans (due_at) WHERE returned_at IS NULL;

CREATE TABLE holds (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id       BIGINT      NOT NULL REFERENCES books (id),
    reader_id     BIGINT      NOT NULL REFERENCES users (id),
    status        VARCHAR(16) NOT NULL DEFAULT 'QUEUED'
                  CHECK (status IN ('QUEUED', 'READY', 'FULFILLED', 'EXPIRED', 'CANCELLED')),
    queued_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    ready_copy_id BIGINT      REFERENCES book_copies (id),
    ready_at      TIMESTAMPTZ,
    expires_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- a reader can hold a given title at most once concurrently
CREATE UNIQUE INDEX uq_holds_active ON holds (book_id, reader_id) WHERE status IN ('QUEUED', 'READY');
CREATE INDEX idx_holds_book_status ON holds (book_id, status);
CREATE INDEX idx_holds_reader ON holds (reader_id);

CREATE TABLE fines (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id    BIGINT      NOT NULL REFERENCES loans (id),
    reader_id  BIGINT      NOT NULL REFERENCES users (id),
    amount_cents INT       NOT NULL CHECK (amount_cents > 0),
    reason     VARCHAR(16) NOT NULL CHECK (reason IN ('OVERDUE', 'LOST')),
    status     VARCHAR(16) NOT NULL DEFAULT 'UNPAID' CHECK (status IN ('UNPAID', 'PAID', 'WAIVED')),
    paid_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_fines_reader_status ON fines (reader_id, status);

-- ---------- patron services ----------

CREATE TABLE favorites (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reader_id  BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    book_id    BIGINT      NOT NULL REFERENCES books (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (reader_id, book_id)
);

CREATE TABLE purchase_suggestions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reader_id  BIGINT       NOT NULL REFERENCES users (id),
    title      VARCHAR(256) NOT NULL,
    author     VARCHAR(256),
    isbn       VARCHAR(20),
    reason     VARCHAR(512),
    status     VARCHAR(16)  NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    handled_by BIGINT       REFERENCES users (id),
    handled_at TIMESTAMPTZ,
    reply      VARCHAR(512),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type       VARCHAR(32)  NOT NULL,
    title      VARCHAR(256) NOT NULL,
    body       TEXT,
    read_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_notifications_user ON notifications (user_id, read_at);

CREATE TABLE circulation_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id BIGINT      REFERENCES users (id),
    action      VARCHAR(32) NOT NULL,
    copy_id     BIGINT      REFERENCES book_copies (id),
    reader_id   BIGINT      REFERENCES users (id),
    detail      JSONB,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_circlogs_created ON circulation_logs (created_at DESC);

-- ---------- papers ----------

CREATE TABLE papers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(512) NOT NULL,
    authors    VARCHAR(512) NOT NULL,
    venue      VARCHAR(256) NOT NULL,
    year       INT          NOT NULL,
    pages      VARCHAR(32),
    abstract   TEXT,
    doi        VARCHAR(128),
    url        VARCHAR(512),
    search_vec tsvector GENERATED ALWAYS AS (
                   to_tsvector('simple',
                       coalesce(title, '') || ' ' || coalesce(authors, '') || ' ' || coalesce(venue, ''))
               ) STORED,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_papers_search_vec ON papers USING gin (search_vec);
CREATE INDEX idx_papers_title_trgm ON papers USING gin (title gin_trgm_ops);
