-- Identity & Access Management: staff role tiers, fine-grained permissions,
-- MFA (TOTP + recovery codes), WebAuthn passkeys, one-time auth tokens, audit.

-- ---------- role tiers ----------

ALTER TABLE users DROP CONSTRAINT users_role_check;
UPDATE users SET role = 'SUPER_ADMIN' WHERE role = 'ADMIN';
ALTER TABLE users ADD CONSTRAINT users_role_check
    CHECK (role IN ('SUPER_ADMIN', 'LIBRARIAN', 'READER'));

ALTER TABLE users DROP CONSTRAINT users_status_check;
ALTER TABLE users ADD CONSTRAINT users_status_check
    CHECK (status IN ('ACTIVE', 'BLOCKED', 'DISABLED'));

ALTER TABLE users
    ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN mfa_enabled    BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN totp_secret    VARCHAR(64);

-- seed accounts are trusted demo identities
UPDATE users SET email_verified = true;

-- ---------- fine-grained staff permissions ----------

CREATE TABLE user_permissions (
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    permission VARCHAR(32) NOT NULL,
    PRIMARY KEY (user_id, permission)
);

-- ---------- one-time tokens (password reset / email verification) ----------

CREATE TABLE auth_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    purpose    VARCHAR(16) NOT NULL CHECK (purpose IN ('RESET', 'VERIFY')),
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_auth_tokens_user ON auth_tokens (user_id, purpose);

-- ---------- MFA recovery codes ----------

CREATE TABLE mfa_recovery_codes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    code_hash  VARCHAR(64) NOT NULL,
    used_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_recovery_codes_user ON mfa_recovery_codes (user_id);

-- ---------- WebAuthn passkeys ----------

CREATE TABLE webauthn_credentials (
    credential_id      VARCHAR(512) PRIMARY KEY,          -- base64url
    user_id            BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    user_entity_id     VARCHAR(64)  NOT NULL,             -- base64url handle exposed to authenticators
    label              VARCHAR(64)  NOT NULL,
    credential_type    VARCHAR(32)  NOT NULL DEFAULT 'public-key',
    public_key_cose    BYTEA        NOT NULL,
    signature_count    BIGINT       NOT NULL DEFAULT 0,
    transports         VARCHAR(128),
    uv_initialized     BOOLEAN      NOT NULL DEFAULT false,
    backup_eligible    BOOLEAN      NOT NULL DEFAULT false,
    backup_state       BOOLEAN      NOT NULL DEFAULT false,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_used_at       TIMESTAMPTZ
);

CREATE INDEX idx_webauthn_user ON webauthn_credentials (user_id);
CREATE INDEX idx_webauthn_entity ON webauthn_credentials (user_entity_id);

-- user id ↔ user-entity handle mapping (opaque handle, never the raw id)
ALTER TABLE users ADD COLUMN webauthn_handle VARCHAR(64) UNIQUE;

-- ---------- authentication audit ----------

CREATE TABLE auth_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT REFERENCES users (id) ON DELETE SET NULL,
    username   VARCHAR(32),
    type       VARCHAR(32) NOT NULL,
    ip         VARCHAR(64),
    user_agent VARCHAR(256),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_auth_events_created ON auth_events (created_at DESC);
CREATE INDEX idx_auth_events_user ON auth_events (user_id);
