#!/usr/bin/env node
/**
 * Catalogue expansion generator.
 *
 * 1. Pulls real bibliographic records (title/author/publisher/year/ISBN-13)
 *    from the Open Library search API across CLC-mapped subjects.
 * 2. Emits backend/src/main/resources/db/migration/V5__catalog_expansion.sql:
 *    - ~300 real books + 2 copies each (barcodes from barcode_seq)
 *    - 34 fictional demo readers
 *    - a deterministic 12-month circulation history (loans / returns /
 *      overdue fines) confined to the NEW books × NEW readers, so the
 *      original demo dataset that integration tests rely on stays untouched.
 *
 * Deterministic: seeded PRNG; re-running against the same API responses
 * yields the same SQL. Usage: node tools/expand-catalog/generate.mjs
 */

const SUBJECTS = [
  ['computer science', 18, 24], ['mathematics', 13, 20], ['physics', 13, 12],
  ['astronomy', 14, 16], ['biology', 15, 16], ['medicine', 16, 16],
  ['history', 11, 20], ['economics', 6, 18], ['philosophy', 2, 16],
  ['psychology', 2, 10], ['art', 10, 16], ['fiction', 9, 24],
  ['education', 7, 14], ['law', 4, 12], ['military history', 5, 10],
  ['linguistics', 8, 12], ['agriculture', 17, 10], ['transportation', 19, 8],
  ['aeronautics', 20, 8], ['environmental science', 21, 10],
  ['sociology', 3, 12], ['communism', 1, 6], ['science', 12, 10],
  ['encyclopedias', 22, 6],
]

const LOCATIONS = { 9: '总馆二层人文区', 10: '总馆二层人文区', 11: '总馆二层人文区', 18: '总馆三层科技区' }

// mulberry32 — tiny seeded PRNG
function rng(seed) {
  return function () {
    seed |= 0; seed = (seed + 0x6d2b79f5) | 0
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}
const rand = rng(20260702)
const pick = (arr) => arr[Math.floor(rand() * arr.length)]
const esc = (s) => String(s).replaceAll("'", "''")

async function fetchSubject(subject, categoryId, want) {
  const url = `https://openlibrary.org/search.json?q=subject:%22${encodeURIComponent(subject)}%22&fields=title,author_name,first_publish_year,isbn,publisher&limit=${want * 4}&sort=editions`
  const res = await fetch(url, { headers: { 'User-Agent': 'libris-catalog-builder (zf1225@ic.ac.uk)' } })
  if (!res.ok) throw new Error(`${subject}: HTTP ${res.status}`)
  const data = await res.json()
  const rows = []
  for (const doc of data.docs ?? []) {
    if (rows.length >= want) break
    const isbn13 = (doc.isbn ?? []).find((i) => /^97[89]\d{10}$/.test(i))
    if (!isbn13 || !doc.title || !doc.author_name?.length) continue
    if (doc.title.length > 200) continue
    rows.push({
      title: doc.title.trim(),
      author: doc.author_name.slice(0, 3).join(', '),
      publisher: (doc.publisher?.[0] ?? 'Unknown').slice(0, 120),
      isbn: isbn13,
      year: doc.first_publish_year && doc.first_publish_year > 1500 ? doc.first_publish_year : null,
      categoryId,
    })
  }
  return rows
}

const SURNAMES = '赵钱孙李周吴郑王冯陈褚卫蒋沈韩杨朱秦尤许何吕施张孔曹严华金魏陶姜'.split('')
const GIVEN = ['伟','芳','娜','敏','静','磊','军','洋','勇','艳','杰','娟','涛','明','超','秀英','霞','平','刚','桂英','鹏','华','红','玉兰','飞','桂兰','鑫','波','斌','宇','浩','凯','秀兰','俊']
const PINYIN = { 赵:'zhao',钱:'qian',孙:'sun',李:'li',周:'zhou',吴:'wu',郑:'zheng',王:'wang',冯:'feng',陈:'chen',褚:'chu',卫:'wei',蒋:'jiang',沈:'shen',韩:'han',杨:'yang',朱:'zhu',秦:'qin',尤:'you',许:'xu',何:'he',吕:'lv',施:'shi',张:'zhang',孔:'kong',曹:'cao',严:'yan',华:'hua',金:'jin',魏:'wei',陶:'tao',姜:'jiang' }
const GPY = { 伟:'wei',芳:'fang',娜:'na',敏:'min',静:'jing',磊:'lei',军:'jun',洋:'yang',勇:'yong',艳:'yan',杰:'jie',娟:'juan',涛:'tao',明:'ming',超:'chao',秀英:'xiuying',霞:'xia',平:'ping',刚:'gang',桂英:'guiying',鹏:'peng',华:'hua',红:'hong',玉兰:'yulan',飞:'fei',桂兰:'guilan',鑫:'xin',波:'bo',斌:'bin',宇:'yu',浩:'hao',凯:'kai',秀兰:'xiulan',俊:'jun' }

function makeReaders(count) {
  const readers = []
  const seen = new Set()
  while (readers.length < count) {
    const s = pick(SURNAMES)
    const g = pick(GIVEN)
    const username = `${PINYIN[s]}${GPY[g]}${readers.length}`
    if (seen.has(username)) continue
    seen.add(username)
    readers.push({
      username,
      name: s + g,
      type: rand() < 0.3 ? 'TEACHER' : 'STUDENT',
      sex: rand() < 0.5 ? '男' : '女',
      birth: `${1975 + Math.floor(rand() * 30)}-${String(1 + Math.floor(rand() * 12)).padStart(2, '0')}-${String(1 + Math.floor(rand() * 28)).padStart(2, '0')}`,
    })
  }
  return readers
}

function main(books) {
  const readers = makeReaders(34)
  const lines = []
  lines.push('-- Generated by tools/expand-catalog/generate.mjs — real Open Library bibliographic')
  lines.push('-- records; fictional demo readers; deterministic 12-month circulation history')
  lines.push('-- (new books × new readers only, so the original test dataset is untouched).')
  lines.push('')

  // books
  lines.push('INSERT INTO books (title, author, publisher, isbn, intro, language, price_cents, pub_date, category_id, cover_url) VALUES')
  const bookValues = books.map((b) =>
    ` ('${esc(b.title)}', '${esc(b.author)}', '${esc(b.publisher)}', '${b.isbn}', NULL, '英文', NULL, ${b.year ? `'${b.year}-01-01'` : 'NULL'}, ${b.categoryId}, 'https://covers.openlibrary.org/b/isbn/${b.isbn}-M.jpg')`)
  lines.push(bookValues.join(',\n') + ';')
  lines.push('')

  // copies: 2 per new book, barcodes from barcode_seq
  lines.push(`INSERT INTO book_copies (book_id, barcode, call_number, location, status)
SELECT b.id,
       'LB' || lpad(nextval('barcode_seq')::text, 6, '0'),
       c.code || '-' || lpad(b.id::text, 4, '0') || '-' || s.n,
       CASE WHEN c.code IN ('I','J','K') THEN '总馆二层人文区'
            WHEN c.code = 'T' THEN '总馆三层科技区'
            ELSE '总馆一层综合区' END,
       'IN_LIBRARY'
FROM books b
JOIN categories c ON c.id = b.category_id
CROSS JOIN (SELECT 1 AS n UNION ALL SELECT 2) s
WHERE b.id > 62;`)
  lines.push('')

  // readers
  lines.push('INSERT INTO users (username, password_hash, display_name, role, email, preferred_locale, email_verified) VALUES')
  lines.push(readers.map((r) =>
    ` ('${r.username}', '$2y$10$phcewVRi9GOjNPOny9yYDeLl6yEAJbsqRuns8yb3eYxIJ2NNhwxiG', '${r.name}', 'READER', '${r.username}@libris.local', 'zh-CN', true)`).join(',\n') + ';')
  lines.push('')
  lines.push('INSERT INTO reader_profiles (user_id, reader_type, sex, birth, address)')
  lines.push('SELECT u.id, v.rt, v.sex, v.birth::date, v.addr FROM users u JOIN (VALUES')
  lines.push(readers.map((r) =>
    ` ('${r.username}', '${r.type}', '${r.sex}', '${r.birth}', '演示地址')`).join(',\n'))
  lines.push(") AS v(username, rt, sex, birth, addr) ON u.username = v.username;")
  lines.push('')

  // circulation history: per-copy sequential timelines on NEW copies only
  const now = new Date('2026-07-01T12:00:00Z').getTime()
  const day = 86400_000
  const loans = []
  const fines = []
  const copyCount = books.length * 2
  for (let c = 0; c < copyCount; c++) {
    if (rand() < 0.35) continue // some copies never circulate
    let cursor = now - 365 * day
    const rounds = 1 + Math.floor(rand() * 6)
    for (let i = 0; i < rounds; i++) {
      cursor += Math.floor(rand() * 40) * day
      const reader = readers[Math.floor(rand() * readers.length)]
      const loanDays = reader.type === 'TEACHER' ? 60 : 30
      const held = Math.floor((0.2 + rand() * 1.3) * loanDays) * day
      const loanedAt = cursor
      const dueAt = loanedAt + loanDays * day
      const returnedAt = loanedAt + held
      if (returnedAt > now - 2 * day) {
        // still out (possibly overdue right now)
        loans.push({ copySeq: c, username: reader.username, loanedAt, dueAt, returnedAt: null })
        break
      }
      loans.push({ copySeq: c, username: reader.username, loanedAt, dueAt, returnedAt })
      if (returnedAt > dueAt) {
        const days = Math.ceil((returnedAt - dueAt) / day)
        fines.push({ loanIdx: loans.length - 1, amount: days * 10, paid: rand() < 0.8 })
      }
      cursor = returnedAt
    }
  }

  const ts = (millis) => `'${new Date(millis).toISOString()}'`
  lines.push('-- 12-month circulation history (deterministic, seed 20260702)')
  lines.push(`WITH new_copies AS (
  SELECT c.id, row_number() OVER (ORDER BY c.id) - 1 AS seq
  FROM book_copies c WHERE c.book_id > 62
)`)
  lines.push('INSERT INTO loans (copy_id, reader_id, loaned_at, due_at, returned_at, operator_id)')
  lines.push('SELECT nc.id, u.id, v.loaned::timestamptz, v.due::timestamptz,')
  lines.push("       CASE WHEN v.returned = '' THEN NULL ELSE v.returned::timestamptz END,")
  lines.push("       (SELECT id FROM users WHERE username = 'admin')")
  lines.push('FROM (VALUES')
  lines.push(loans.map((l) =>
    ` (${l.copySeq}, '${l.username}', ${ts(l.loanedAt)}, ${ts(l.dueAt)}, ${l.returnedAt ? ts(l.returnedAt) : "''"})`).join(',\n'))
  lines.push(') AS v(seq, username, loaned, due, returned)')
  lines.push('JOIN new_copies nc ON nc.seq = v.seq')
  lines.push('JOIN users u ON u.username = v.username;')
  lines.push('')

  // mark still-out copies
  lines.push(`UPDATE book_copies SET status = 'ON_LOAN'
WHERE id IN (SELECT copy_id FROM loans WHERE returned_at IS NULL);`)
  lines.push('')

  // fines: locate the loan by copy seq + loaned_at
  if (fines.length > 0) {
    lines.push('INSERT INTO fines (loan_id, reader_id, amount_cents, reason, status, paid_at)')
    lines.push('SELECT l.id, l.reader_id, v.amount, \'OVERDUE\',')
    lines.push("       CASE WHEN v.paid THEN 'PAID' ELSE 'UNPAID' END,")
    lines.push('       CASE WHEN v.paid THEN l.returned_at ELSE NULL END')
    lines.push('FROM (VALUES')
    lines.push(fines.map((f) => {
      const l = loans[f.loanIdx]
      return ` (${l.copySeq}, ${ts(l.loanedAt)}, ${f.amount}, ${f.paid})`
    }).join(',\n'))
    lines.push(') AS v(seq, loaned, amount, paid)')
    lines.push(`JOIN (SELECT c.id, row_number() OVER (ORDER BY c.id) - 1 AS seq
      FROM book_copies c WHERE c.book_id > 62) nc ON nc.seq = v.seq`)
    lines.push('JOIN loans l ON l.copy_id = nc.id AND l.loaned_at = v.loaned::timestamptz;')
  }

  return { sql: lines.join('\n') + '\n', loanCount: loans.length, fineCount: fines.length, readerCount: readers.length }
}

const seen = new Set([
  // ISBNs already present in V2 seed — avoid duplicates
  '9787010083872','9787506394864','9787807023777','9787501162734','9787010151441','9787532776627','9787542629845','9787101076080','9787111126768','9787508693101','9787508684031','9787508648286','9787511704375','9787100124508','9787100170932','9787536692930','9787536693968','9787229030933','9787506365437','9787544253994','9787020002207','9787020024759','9787530216781','9787544258609','9787544270878','9787530216835','9787530216859','9787513325745','9787020042494','9787530210291','9787020033294','9787532725694','9787505414709','9787544138000','9787539943893','9787020125265','9787550265608','9787549408183','9787550252585','9787508647357','9787508672069','9787108009821','9787301109489','9787801656087','9787535732309','9787030029331','9787309048285','9787532736044','9787115366016','9787508634203','9787508639826','9787213066856','9787111544937','9787111407010','9780262046305','9780262510875','9780131103627','9780132350884','9781449373320','9787121022982','9787111075752','9787532772892','9787513313735',
])

let all = []
for (const [subject, categoryId, want] of SUBJECTS) {
  try {
    const rows = await fetchSubject(subject, categoryId, want)
    for (const row of rows) {
      if (seen.has(row.isbn)) continue
      seen.add(row.isbn)
      all.push(row)
    }
    console.error(`${subject}: +${rows.length}`)
  } catch (e) {
    console.error(`${subject}: FAILED ${e.message}`)
  }
}

console.error(`total books: ${all.length}`)
const { sql, loanCount, fineCount, readerCount } = main(all)
const fs = await import('node:fs')
fs.writeFileSync(new URL('../../backend/src/main/resources/db/migration/V5__catalog_expansion.sql', import.meta.url), sql)
console.error(`written V5: ${all.length} books, ${readerCount} readers, ${loanCount} loans, ${fineCount} fines`)
